/**
 * Generates the store listing graphics from the real, running extension.
 *
 * Chrome Web Store requirements this satisfies:
 *   - at least one 1280x800 screenshot (up to 5)      → store/assets/screenshot-*.png
 *   - a 440x280 small promo tile (required)           → store/assets/promo-tile-440x280.png
 *   - an optional 1400x560 marquee tile               → store/assets/marquee-1400x560.png
 *   - a 128x128 store icon (already in src/icons)     → store/assets/icon-128.png
 *
 * The screenshots are captured from the built extension against the fixture feed,
 * so they show the shipped UI. Swap in shots from your own logged-in feed if you
 * prefer — same dimensions.
 *
 * Usage: node scripts/store-assets.mjs
 */
import { chromium } from "playwright";
import { mkdtemp, mkdir, readFile, writeFile, copyFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { startMockServer, readFixture } from "../test/mock-typesafe-server.mjs";
import { DEFAULT_SETTINGS, STORAGE_KEYS } from "../src/shared/settings.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = resolve(root, "dist/chrome");
const outDir = resolve(root, "store/assets");

const TINY_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
  "base64",
);

const STORE_ASSETS_README = `# Store listing assets

Generated by \`npm run store:assets\` — do not hand-edit, edit \`scripts/store-assets.mjs\` and regenerate.

| File | Size | Where it goes |
| --- | --- | --- |
| \`screenshot-1-feed.png\` | 1280x800 | Chrome Web Store screenshot 1, AMO screenshot 1 |
| \`screenshot-2-explanation.png\` | 1280x800 | Chrome screenshot 2, AMO screenshot 2 |
| \`screenshot-3-popup.png\` | 1280x800 | Chrome screenshot 3, AMO screenshot 3 |
| \`screenshot-4-settings.png\` | 1280x800 | Chrome screenshot 4, AMO screenshot 4 |
| \`promo-tile-440x280.png\` | 440x280 | Chrome small promo tile (required) |
| \`marquee-1400x560.png\` | 1400x560 | Chrome marquee promo tile (optional) |
| \`icon-128.png\` | 128x128 | Chrome store icon, AMO icon |

The screenshots show the real shipped UI, captured from the built extension against a fixture feed. If you want the
feed shot to show your own content, take a 1280x800 screenshot of your logged-in feed with highlights visible and
replace \`screenshot-1-feed.png\`; the store only cares about the dimensions.

Both stores reject images with a different aspect ratio, so keep every replacement at the exact size above.
`;

/** Read width/height straight out of the PNG IHDR so we can assert the exact size. */
function pngSize(buffer) {
  if (buffer.readUInt32BE(0) !== 0x89504e47) throw new Error("not a PNG");
  return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
}

async function save(page, file, expected) {
  const buffer = await page.screenshot({ path: resolve(outDir, file) });
  const size = pngSize(buffer);
  if (size.width !== expected.width || size.height !== expected.height) {
    throw new Error(`${file}: got ${size.width}x${size.height}, expected ${expected.width}x${expected.height}`);
  }
  console.log(`${file.padEnd(34)} ${size.width}x${size.height}  ${(buffer.length / 1024).toFixed(0)} KB`);
  return buffer;
}

/* ------------------------------------------------------------------- setup */

await mkdir(outDir, { recursive: true });
const server = await startMockServer();
const raw = await readFixture();
const pageCss = raw.match(/<style>([\s\S]*?)<\/style>/)?.[1] ?? "";
const fixture = raw.replace(/<style>[\s\S]*?<\/style>/, '<link rel="stylesheet" href="/fixture.css" />');
const iconDataUrl = `data:image/png;base64,${(await readFile(resolve(root, "src/icons/icon-128.png"))).toString("base64")}`;

const context = await chromium.launchPersistentContext(await mkdtemp(resolve(tmpdir(), "deslopify-store-")), {
  channel: "chromium",
  headless: true,
  viewport: { width: 1280, height: 800 },
  args: [`--disable-extensions-except=${DIST}`, `--load-extension=${DIST}`],
});

const worker = context.serviceWorkers()[0] ?? (await context.waitForEvent("serviceworker"));
await worker.evaluate(
  async ([key, settings]) => chrome.storage.local.set({ [key]: settings }),
  [STORAGE_KEYS.settings, { ...DEFAULT_SETTINGS, apiKey: "store-assets", baseUrl: server.endpoint }],
);

await context.route("https://www.linkedin.com/**", (route) => {
  const url = route.request().url();
  if (url.endsWith(".png")) return route.fulfill({ status: 200, contentType: "image/png", body: TINY_PNG });
  if (url.endsWith("/fixture.css")) return route.fulfill({ status: 200, contentType: "text/css", body: pageCss });
  return route.fulfill({ status: 200, contentType: "text/html", body: fixture });
});

/* ------------------------------------------------------- feed screenshots */

const feed = await context.newPage();
await feed.setViewportSize({ width: 1280, height: 800 });
await feed.goto("https://www.linkedin.com/feed/");
for (let y = 0; y <= (await feed.evaluate(() => document.body.scrollHeight)); y += 400) {
  await feed.evaluate((top) => window.scrollTo(0, top), y);
  await feed.waitForTimeout(140);
}
await feed.evaluate(() => window.scrollTo(0, 0));
await feed.waitForFunction(() => document.querySelectorAll("[data-deslopify]").length >= 5, undefined, { timeout: 30_000 });
await feed.waitForTimeout(500);
await save(feed, "screenshot-1-feed.png", { width: 1280, height: 800 });

await feed.locator(".deslopify-badge-host .pill").nth(2).click(); // the slop post
await feed.waitForTimeout(300);
await save(feed, "screenshot-2-explanation.png", { width: 1280, height: 800 });

/* ------------------------------------------------- extension page shots */

const extensionId = new URL(worker.url()).host;
const STAGE_CSS = `
  html, body { width: 1280px !important; height: 800px !important; margin: 0 !important; overflow: hidden !important; }
  body {
    background: radial-gradient(1200px 600px at 20% -10%, #1b2430 0%, #10131a 55%, #0b0e13 100%) !important;
    color: #e8eaed !important;
    display: flex !important; align-items: center !important; justify-content: center !important;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif !important;
  }
  body::before {
    content: "Deslopify — golden nuggets, useful posts, and slop, graded as you scroll";
    position: fixed; top: 44px; left: 0; right: 0; text-align: center;
    font-size: 20px; font-weight: 600; letter-spacing: -0.01em; color: #f2f4f7;
  }
  body::after {
    content: "No account, no analytics · runs on your own key, or demo mode with no key at all";
    position: fixed; bottom: 44px; left: 0; right: 0; text-align: center;
    font-size: 13px; color: #9aa1ab;
  }
  /* The settings page pins its save bar to the viewport; inside the product-shot
     card it should sit in the flow instead. */
  footer.save-bar { position: static !important; }
`;

async function stageExtensionPage(path, width, file) {
  const stage = await context.newPage();
  await stage.setViewportSize({ width: 1280, height: 800 });
  await stage.goto(`chrome-extension://${extensionId}/${path}`);
  await stage.waitForTimeout(400);
  await stage.addStyleTag({ content: STAGE_CSS });
  // Move the page's own content into a floating card so it reads as a product shot.
  await stage.evaluate((cardWidth) => {
    const card = document.createElement("div");
    card.style.cssText = `width:${cardWidth}px;max-height:640px;overflow:auto;border-radius:16px;background:#16181d;border:1px solid rgba(255,255,255,.12);box-shadow:0 24px 60px rgba(0,0,0,.55);`;
    while (document.body.firstChild) card.append(document.body.firstChild);
    document.body.append(card);
    // Re-run the page's own renderers against the moved nodes.
    window.dispatchEvent(new Event("resize"));
  }, width);
  await stage.waitForTimeout(400);
  await save(stage, file, { width: 1280, height: 800 });
  await stage.close();
}

await stageExtensionPage("popup.html", 340, "screenshot-3-popup.png");
await stageExtensionPage("options.html", 760, "screenshot-4-settings.png");

/* ------------------------------------------------------------ promo tiles */

const CHIPS = [
  ["golden nugget", "#f0b429"],
  ["useful", "#2f9e6f"],
  ["slop", "#d9534f"],
];

async function promo(file, width, height, { scale }) {
  const tile = await context.newPage();
  await tile.setViewportSize({ width, height });
  const chips = CHIPS.map(
    ([label, color]) =>
      `<span style="display:inline-flex;align-items:center;gap:8px;padding:${scale(5)}px ${scale(14)}px;border-radius:999px;background:${color}22;border:1px solid ${color};color:#f2f4f7;font-size:${scale(15)}px;font-weight:600">
        <span style="width:${scale(9)}px;height:${scale(9)}px;border-radius:999px;background:${color}"></span>${label}
      </span>`,
  ).join("");
  await tile.setContent(
    `<!doctype html><html><body style="margin:0;width:${width}px;height:${height}px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:${scale(16)}px;background:radial-gradient(${scale(700)}px ${scale(380)}px at 15% -20%, #1b2430 0%, #10131a 55%, #0b0e13 100%);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
      <img src="${iconDataUrl}" width="${scale(56)}" height="${scale(56)}" style="border-radius:${scale(14)}px" alt="" />
      <div style="font-size:${scale(34)}px;font-weight:700;color:#f2f4f7;letter-spacing:-0.02em">Deslopify</div>
      <div style="font-size:${scale(16)}px;color:#9aa1ab;max-width:${scale(560)}px;text-align:center;line-height:1.4">
        Grades every post in your feed as you scroll
      </div>
      <div style="display:flex;gap:${scale(10)}px">${chips}</div>
    </body></html>`,
  );
  await tile.waitForTimeout(250);
  await save(tile, file, { width, height });
  await tile.close();
}

await promo("promo-tile-440x280.png", 440, 280, { scale: (n) => Math.round(n * 0.72) });
await promo("marquee-1400x560.png", 1400, 560, { scale: (n) => Math.round(n * 1.45) });

/* ------------------------------------------------------------------- icon */

await copyFile(resolve(root, "src/icons/icon-128.png"), resolve(outDir, "icon-128.png"));
console.log("icon-128.png".padEnd(34) + "128x128   (copied from src/icons)");

await context.close();
await server.close();
await writeFile(resolve(outDir, "README.md"), STORE_ASSETS_README);
console.log(`\nstore assets written to ${outDir}`);
